"""Reports & PDF export page."""
import streamlit as st
from datetime import datetime
from frontend.components.cards import section_title


def render() -> None:
    st.title("📄 Reports")
    st.caption("Generate and download a patient screening report as PDF.")
    st.divider()

    patient = st.session_state.get("current_patient", {})
    speech = st.session_state.get("speech_result")
    handwriting = st.session_state.get("handwriting_result")
    fusion = st.session_state.get("fusion_result")

    section_title("Report Preview")

    if not patient:
        st.warning("No patient loaded. Please complete Patient Screening first.")
    else:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        st.markdown(f"""
        ---
        ## 🧠 NeuroSense AI — Screening Report
        **Generated:** {timestamp}

        ### Patient Information
        | Field | Value |
        |---|---|
        | Name | {patient.get('name', '—')} |
        | Age | {patient.get('age', '—')} |
        | Gender | {patient.get('gender', '—')} |
        | Language | {patient.get('language', '—')} |
        | Notes | {patient.get('notes', '—')} |

        ### Speech Analysis
        {f"- **Probability:** {speech['probability']*100:.2f}%" if speech else "- *Not performed*"}
        {f"- **Prediction:** {speech['label']}" if speech else ""}

        ### Handwriting Analysis
        {f"- **Probability:** {handwriting['probability']*100:.2f}%" if handwriting else "- *Not performed*"}
        {f"- **Prediction:** {handwriting['label']}" if handwriting else ""}

        ### Fusion Result
        {f"- **Final Probability:** {fusion['final_prob']*100:.2f}%" if fusion else "- *Not performed*"}
        {f"- **Prediction:** {fusion['prediction']}" if fusion else ""}
        {f"- **Risk Level:** {fusion['risk_level']}" if fusion else ""}

        ---
        *This report is generated by NeuroSense AI and is intended for clinical support only.
        Please consult a qualified neurologist for diagnosis.*
        """)

    st.divider()
    section_title("Download PDF")

    if st.button("📥 Generate & Download PDF Report", type="primary", use_container_width=True):
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.pdfgen import canvas
            import io

            buffer = io.BytesIO()
            c = canvas.Canvas(buffer, pagesize=A4)
            w, h = A4

            c.setFont("Helvetica-Bold", 18)
            c.drawString(50, h - 60, "NeuroSense AI — Screening Report")

            c.setFont("Helvetica", 11)
            ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            c.drawString(50, h - 85, f"Generated: {ts}")

            y_pos = h - 130
            lines = []
            if patient:
                lines += [
                    "PATIENT INFORMATION",
                    f"  Name    : {patient.get('name', '—')}",
                    f"  Age     : {patient.get('age', '—')}",
                    f"  Gender  : {patient.get('gender', '—')}",
                    f"  Language: {patient.get('language', '—')}",
                    f"  Notes   : {patient.get('notes', '—')}",
                    "",
                ]
            if speech:
                lines += [
                    "SPEECH ANALYSIS",
                    f"  Probability : {speech['probability']*100:.2f}%",
                    f"  Prediction  : {speech['label']}",
                    "",
                ]
            if handwriting:
                lines += [
                    "HANDWRITING ANALYSIS",
                    f"  Probability : {handwriting['probability']*100:.2f}%",
                    f"  Prediction  : {handwriting['label']}",
                    "",
                ]
            if fusion:
                lines += [
                    "FUSION RESULT",
                    f"  Final Probability : {fusion['final_prob']*100:.2f}%",
                    f"  Prediction        : {fusion['prediction']}",
                    f"  Risk Level        : {fusion['risk_level']}",
                    "",
                ]
            lines.append("Disclaimer: For clinical support use only. Consult a neurologist for diagnosis.")

            for line in lines:
                if line.isupper():
                    c.setFont("Helvetica-Bold", 12)
                else:
                    c.setFont("Helvetica", 11)
                c.drawString(50, y_pos, line)
                y_pos -= 18
                if y_pos < 60:
                    c.showPage()
                    y_pos = h - 60

            c.save()
            buffer.seek(0)

            st.download_button(
                label="⬇️ Download PDF",
                data=buffer,
                file_name=f"neurosense_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
                mime="application/pdf",
            )
        except ImportError:
            st.error("reportlab is required. Add `reportlab` to requirements.txt and reinstall.")
        except Exception as e:
            st.error(f"PDF generation failed: {e}")
